const test=require('node:test');const assert=require('node:assert/strict');
async function core(){return import('../photo-ai-assisted-core.mjs');}
test('structured data validates fields and preserves units',async()=>{const c=await core();const r=c.validateAssistedRecord({id:'d1',date:'2026-08-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:'55',unit:'°C',printedUnit:'°C',recordedUnit:'°C'}]}});assert.equal(r.structuredData.source,'assisted_form');assert.equal(r.structuredData.measurements[0].value,55);assert.equal(c.validateField('generator','3/5'),null);assert.equal(c.validateField('generator','3/4'),'3/4');});
test('AQS August average ignores null, other month and other item',async()=>{const c=await core();const rows=[{id:'a',date:'2026-08-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:50}]}},{id:'b',date:'2026-08-10',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:55}]}},{id:'c',date:'2026-08-20',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:60},{section:'aqs',item:'02',type:'temperature',value:99}] }},{id:'d',date:'2026-09-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:100}]}},{id:'e',date:'2026-08-30',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:null}]}}];const a=c.aggregateMeasurements(rows,{section:'aqs',item:'01',type:'temperature',from:'2026-08-01',to:'2026-08-31'});assert.deepEqual(a,{count:3,average:55,min:50,max:60,last:60});});
test('history mirror does not duplicate metrics and checks remain distinct',async()=>{const c=await core();const rows=[{id:'d1',date:'2026-08-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:50}],checks:[{section:'aqs',item:'01',status:'OK'}]}},{id:'diary_d1',diaryId:'d1',date:'2026-08-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:50}],checks:[{section:'aqs',item:'01',status:'OK'}]}}];assert.equal(c.aggregateMeasurements(rows,{section:'aqs',item:'01'}).count,1);assert.equal(c.countChecks(rows,'OK'),1);assert.equal(c.countChecks(rows,'NOK'),0);});
test('legacy records without structuredData remain valid',async()=>{const c=await core();const r=c.validateAssistedRecord({id:'old',date:'2026-08-01',text:'ocorrência'});assert.equal(r.id,'old');assert.equal(r.structuredData,undefined);assert.equal(c.aggregateMeasurements([r],{}).count,0);});
test('structured query returns deterministic AQS metrics and ambiguity',async()=>{const c=await core();const rows=[1,10,20].map((d,i)=>({id:`a${i}`,date:`2026-08-${String(d).padStart(2,'0')}`,structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:[50,55,60][i]}]}}));rows.push({id:'b',date:'2026-08-15',structuredData:{measurements:[{section:'aqs',item:'02',type:'temperature',value:70}]}});assert.equal(c.tryStructuredQuery('Qual foi a temperatura média do AQS 01 em agosto?',rows).result,55);assert.equal(c.tryStructuredQuery('Qual foi a temperatura máxima do AQS 01 em agosto?',rows).result,60);assert.equal(c.tryStructuredQuery('Qual foi a mínima do AQS 01 em agosto?',rows).result,50);assert.equal(c.tryStructuredQuery('Qual foi a última temperatura do AQS 01 em agosto?',rows).result,60);assert.equal(c.tryStructuredQuery('Qual foi a média do AQS em agosto?',rows).status,'AMBIGUOUS_SUBITEM');});
test('structured query counts NOK only',async()=>{const c=await core();const rows=[['OK'],['OK'],['NOK'],['Não registado']].map(([status],i)=>({id:String(i),date:'2026-08-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'check',status}]}}));assert.equal(c.tryStructuredQuery('Quantos NOK teve o AQS 01 em agosto?',rows).result,1);});

test('regressions: descending input, period checks, mirrors and numeric validation',async()=>{
 const c=await core();const rows=[20,10,1].map((d,i)=>({id:String(d),date:`2026-08-${String(d).padStart(2,'0')}`,structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value:[60,55,50][i],unit:'°C'},{section:'aqs',item:'01',type:'check',status:i===1?'NOK':'OK'}]}}));
 rows.unshift({...rows[0],id:'diary_20',diaryId:20,source:'diary'});rows.push({id:'sep',date:'2026-09-01',structuredData:{measurements:[{section:'aqs',item:'01',type:'check',status:'NOK'}]}});
 assert.equal(c.tryStructuredQuery('última AQS01 em agosto de 2026',rows).result,60);assert.equal(c.tryStructuredQuery('NOK AQS01 em agosto de 2026',rows).result,1);assert.equal(c.tryStructuredQuery('NOK AQS04 em agosto de 2026',rows).status,'INSUFFICIENT_DATA');
 assert.equal(c.tryStructuredQuery('manutenção do AQS',rows),null);assert.equal(c.tryStructuredQuery('média AQS 10',rows).status,'AMBIGUOUS_SUBITEM');assert.equal(c.tryStructuredQuery('média AQS 01 desde janeiro até agosto',rows).status,'INSUFFICIENT_DATA');
 assert.equal(c.validateField('number','0x20'),null);assert.equal(c.validateField('number','1e3'),null);assert.equal(c.normalizeStructuredData({measurements:[{section:'generator',type:'level',value:'3/4'}]}).measurements[0].value,'3/4');
 assert.equal(c.dedupeDiaryHistory([{text:'x'},{text:'x'}]).length,2);assert.equal(c.dedupeDiaryHistory([{id:1,fichaId:'44'},{id:1,fichaId:'45'}]).length,2);assert.equal(c.dedupeDiaryHistory([{id:'diary_a',diaryId:'a',source:'diary'}]).length,1);
});

test('canonical value wins over stale mirror in both orders; last follows date and time',async()=>{
 const c=await core();
 const row=(id,date,value,timestamp)=>({id,date,timestamp,fichaId:'44',structuredData:{measurements:[{section:'aqs',item:'01',type:'temperature',value,unit:'°C'}]}});
 const canonical=row('abc123','2026-08-20',60,'2026-08-20T12:00:00Z');
 const stale={...row('diary_abc123','2026-08-20',999,'2026-08-20T12:00:00Z'),diaryId:'abc123',source:'diary'};
 for(const pair of [[stale,canonical],[canonical,stale]]){
  assert.deepEqual(c.dedupeDiaryHistory(pair),[canonical]);
  const rows=[...pair,row('early','2026-08-01',50),row('mid','2026-08-10',55),row('sept','2026-09-01',90)];
  assert.deepEqual(c.aggregateMeasurements(rows,{section:'aqs',item:'01',type:'temperature',from:'2026-08-01',to:'2026-08-31'}),{count:3,average:55,min:50,max:60,last:60});
 }
 const sameDay=[row('latest','2026-08-20',60,'2026-08-20T12:00:00Z'),row('earlier','2026-08-20',55,'2026-08-20T09:00:00Z')];
 assert.equal(c.aggregateMeasurements(sameDay).last,60);
});
