import {generateKeyPairSync,sign} from 'node:crypto';
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048});
export const jwk={...publicKey.export({format:'jwk'}),kid:'test-key',alg:'RS256',use:'sig'};
const b64=value=>Buffer.from(typeof value==='string'?value:JSON.stringify(value)).toString('base64url');
export function token(payload={},header={}){const h=b64({alg:'RS256',kid:'test-key',...header}),p=b64({aud:'manutencao-semanal',iss:'https://securetoken.google.com/manutencao-semanal',exp:Math.floor(Date.now()/1000)+3600,iat:Math.floor(Date.now()/1000)-1,sub:'allowed-user',...payload});return `${h}.${p}.${sign('RSA-SHA256',Buffer.from(`${h}.${p}`),privateKey).toString('base64url')}`;}
export function keyFetch(){return async()=>new Response(JSON.stringify({keys:[jwk]}),{headers:{'cache-control':'public, max-age=300'}});}
export function env(overrides={}){const locks=new Map();return {NODE_ENV:'staging',PHOTO_AI_ENABLED:'true',PHOTO_AI_FREE_ONLY:'true',PHOTO_AI_AUTH_REVOCATION_MODE:'signature-only',FIREBASE_PROJECT_ID:'manutencao-semanal',PHOTO_AI_ORIGINS:'https://scaixeir75.github.io',PHOTO_AI_MODEL:'@cf/meta/llama-3.2-11b-vision-instruct',PHOTO_AI_TIMEOUT_MS:'100',PHOTO_AI_UIDS:'allowed-user',AI:{run:async()=>({response:JSON.stringify(complete())})},PHOTO_AI_RATE_LIMITER:{idFromName:name=>name,get:()=>({acquire:async()=>{if(locks.has('lock'))return null;const id='lock';locks.set(id,true);return id;},release:async id=>locks.delete(id)})},...overrides};}
export function complete(){const fields={};for(const name of ['date','equipment','work','status','notes','anomaly'])fields[name]={value:name==='date'?'2026-09-05':name==='status'?'Concluído':'texto',confidence:'Reconhecido',evidence:'texto',reason:''};return {schemaVersion:1,fields,warnings:[]};}
export function request({body,origin='https://scaixeir75.github.io',auth=token(),signal}={}){return new Request('https://worker.test/v1/photo-ai/analyze',{method:'POST',signal,headers:{origin,authorization:`Bearer ${auth}`,'content-type':'application/json'},body:JSON.stringify(body||{image:Buffer.from('synthetic').toString('base64'),mime:'image/png',context:{fichaId:'41',equipment:'Quadros',week:'36'}})});}
